name: smart_waste_management
description: "Smart Waste Management - Digital Waste Collection System"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.9.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # UI & Design
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  flutter_svg: ^2.0.9
  lottie: ^2.7.0
  animations: ^2.0.7

  # State Management & Storage
  get: ^4.6.6
  pdf: ^3.10.7
  printing: ^5.13.4
  get_storage: ^2.1.1
  get_it: ^7.6.0
  flutter_dotenv: ^5.1.0

  # Firebase Dependencies
  firebase_core: ^3.14.0
  firebase_auth: ^5.1.4
  cloud_firestore: ^5.4.4
  firebase_storage: ^12.3.4
  firebase_messaging: ^15.1.5

  # Image & Cloud Storage
  cloudinary_public: ^0.21.0
  cloudinary: ^1.2.0
  image_picker: ^1.0.4
  camera: ^0.10.5
  cached_network_image: ^3.3.0
  image: ^4.1.4

  # Location & Maps
  geolocator: ^11.0.1
  google_maps_flutter: ^2.2.3
  geocoding: ^2.1.1
  flutter_map: ^6.1.0
  latlong2: ^0.9.1

  # QR Code & NFC
  qr_flutter: ^4.1.0
  mobile_scanner: ^3.5.5
  rxdart: ^0.27.7

  # PDF Generation & Reports
  syncfusion_flutter_charts: ^28.1.38
  fl_chart: ^0.68.0

  # Payment Integration (Choose based on region)
  # stripe_payment: ^1.1.8  # For Stripe
  # razorpay_flutter: ^1.3.7  # For Razorpay
  
  # Permissions & File Handling
  permission_handler: ^11.0.1
  file_picker: ^8.0.0
  path_provider: ^2.1.1
  path: ^1.9.0

  # Networking & API
  dio: ^5.4.0
  http: ^1.2.0

  # Date & Time
  intl: ^0.20.2

  # Notifications
  flutter_local_notifications: ^17.2.0
  awesome_notifications: ^0.10.1

  # Loading & Animations
  flutter_spinkit: ^5.2.0

  # Sharing & Utils
  share_plus: ^10.1.3
  url_launcher: ^6.2.1

  # Offline Storage
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # Email
  emailjs: ^4.0.0

  # Localization
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  mockito: ^5.4.4
  build_runner: ^2.4.7
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/animations/
    - assets/fonts/

  generate: true